### ISSUE TITLE
ProxyHandler has been changed

### ISSUE THREAD

**Issue by monolithed** [tvcutsem/proxy-handlers#1]
it seems the ProxyHandler has been [changed](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-proxy-object-internal-methods-and-internal-slots)

**Comment by tvcutsem** [comment]
The handlers defined in this library are not standardized. For the standardized proxy handler API, please see the [harmony-reflect](https://github.com/tvcutsem/harmony-reflect) library. Its [docs](https://github.com/tvcutsem/harmony-reflect/blob/master/doc/handler_api.md) should be up-to-date. If you spot any specific differences with the spec, do let me know.

Meanwhile, I'll put up a warning in the README that the handlers defined in this library are not standardized to avoid any confusion.

**Comment by monolithed** [comment]
Oh, now it is clear.

I was confused following sentence:

> This library provides a number of **predefined** ECMAScript 6 Proxy handlers.

And 

> VirtualHandler was then renamed to just Handler
> http://wiki.ecmascript.org/doku.php?id=harmony:virtual_object_api

**Comment by tvcutsem** [comment]
I updated the README to avoid the term "predefined". Thanks for the feedback.
